### ISSUE TITLE
i am

### ISSUE THREAD

**Issue by Daybreak-keks** [DeadxFunnies/-Rage-Multitool-NewsLetter-#1]
the fucking?

Spazzy could you place tell me when you're coming back to discord? I'm willing to teach you some Python or JS, idk.

My tag: Windent#5598
UserID: 451556989143875584

**Comment by DeadxFunnies** [comment]
I'm not coming back. The special victims unit got involved.

Also what's a good name for a hacking group I want a iconic name that's simple like cubed. Cubed has a good name I want one for mine.

**Comment by Daybreak-keks** [comment]
You're not a hacker, Spazzy.
Cubed and CG has been dead for months.

**Comment by Daybreak-keks** [comment]
Also you're missing out, as I said, I'm willing to teach you some JS or Python
